#!/usr/bin/env bash

# 
# Banner
#

echo "
Welcome to the O.C. Tanner OSX quick start

Last tested 2013-03-04 on OSX Snow Leopard

Be sure to install either Xcode or Xcode Commandline Tools before running this script.

https://itunes.apple.com/us/app/xcode/id497799835?mt=12
https://developer.apple.com/downloads/index.action

See Matthew if you have problems or questions.
"

#
# SSH keys configuration
#

echo "Checking for SSH key, generating one if it doesn't exist ..."
  [[ -f ~/.ssh/id_rsa.pub ]] || ssh-keygen -t rsa

echo "Copying public key to clipboard. Paste it into your Github account ..."
  [[ -f ~/.ssh/id_rsa.pub ]] && cat ~/.ssh/id_rsa.pub | pbcopy
  open https://github.com/account/ssh

#
# Homebrew
#

echo "Installing Homebrew, a good OS X package manager ..."
  ruby -e "$(curl -fsSkL raw.github.com/mxcl/homebrew/go)"
  brew update
  brew doctor
  brew tap homebrew/dupes

#
# Bash Completion
#

echo "Installing and configuring bash completion"
  brew install bash-completion
  echo "
if [ -f `brew --prefix`/etc/bash_completion ]; then
    . `brew --prefix`/etc/bash_completion
fi
" >> ~/.bashrc
  source ~/.bashrc
  ln -s "/usr/local/Library/Contributions/brew_bash_completion.sh" "/usr/local/etc/bash_completion.d"

#
# Git and Build Tools
#

echo "Installing git"
  brew install git

echo "Installing autoconf, automake and apple-gcc42"
  brew install autoconf 
  brew install automake 
  brew install apple-gcc42

echo "Installing qt to support capybara"
echo "  See https://github.com/thoughtbot/capybara-webkit/wiki/Installing-Qt-and-compiling-capybara-webkit for more info"
  brew install qt

#
# RVM, Ruby and Rails
#

echo "Installing RVM and Ruby"
  curl -L https://get.rvm.io | bash -s stable
  source ~/.rvm/scripts/rvm
  rvm pkg install openssl
  rvm install 1.9.3
  rvm use 1.9.3 --default
  gem install rails

#
# Postgres
#

echo "Installing and setting up Postgres"
  brew install postgres
  if [ ! -d "/usr/local/var/postgres" ]; then
    initdb /usr/local/var/postgres -E utf8
  fi
  pg_ctl -D /usr/local/var/postgres -l /usr/local/var/postgres/server.log start

#
# NVM, NodeJS and libs
#

echo "Installing NVM"
  git clone https://github.com/creationix/nvm.git ~/.nvm
  echo "
# NVM setup 
source ~/.nvm/nvm.sh
" >> ~/.bashrc
  source ~/.bashrc

echo "Installing NodeJS"
  nvm install v0.8.2
  nvm alias default v0.8.2
  nvm use v0.8.2

echo "Installing Foreman, CoffeeScript, Buster, i18next and Nodemon"
  npm install foreman -g
  npm install coffee-script -g
  npm install mocha -g
  npm install i18next
  npm install nodemon -g
