#!/usr/bin/env bash

echo "Checking for SSH key, generating one if it doesn't exist ..."
  [[ -f ~/.ssh/id_rsa.pub ]] || ssh-keygen -t rsa

echo "Copying public key to clipboard. Paste it into your Github account ..."
  [[ -f ~/.ssh/id_rsa.pub ]] && cat ~/.ssh/id_rsa.pub | pbcopy
  open https://github.com/account/ssh

echo "Installing Homebrew, a good OS X package manager ..."
  /usr/bin/ruby -e "$(/usr/bin/curl -fksSL https://raw.github.com/mxcl/homebrew/master/Library/Contributions/install_homebrew.rb)"
  brew update

echo "Put Homebrew location earlier in PATH ..."
  echo "
# Homebrew config
export PATH=\"/usr/local/bin:\$PATH\"
export MANPATH=\"/usr/local/share/man:\$MANPATH\"
" >> ~/.zshrc
  source ~/.zshrc

echo "Installing Postgres, a good open source relational database ..."
  brew install postgres

echo "Installing MySQL, another goof open source relational database ..."
  brew install mysql

echo "Installing ack, a good way to search through files ..."
  brew install ack

echo "Installing tmux, a good way to save project state and switch between projects ..."
  brew install tmux

echo "Installing ImageMagick, good for cropping and re-sizing images ..."
  brew install imagemagick

echo "Installing rbenv, for managing rubies"
  brew install rbenv
  echo "
# rvenv config
export PATH=\"\$HOME/.rbenv/bin:\$PATH\"
eval \"\$(rbenv init -)\"
" >> ~/.zshrc
  source ~/.zshrc

echo "Installing ruby-build, for building rubies"
  brew install ruby-build

bash < <(curl -s https://raw.github.com/janogonzalez/laptop/master/ruby)
